### ISSUE TITLE
minor annoyance on windows - cmd char limit for commands...

### ISSUE THREAD

**Issue by jmerc77** [TotalTechGeek/pictoprime#16]
I seem to not be able to use a width more than 63. if i try i get this error:

`The command line is too long.`

powershell has a much bigger limit but the code here seems to be only capable of using cmd. the error ocurrs on the call to openssl.

[pictoprime limitation.txt](https://github.com/TotalTechGeek/pictoprime/files/8790514/pictoprime.limitation.txt)

**Comment by TotalTechGeek** [comment]
I've pushed a new version that calls OpenSSL a bit differently, increasing the line length that is possible. Instead of an 8K character limit, it is now roughly a 32K character limit. 

This is a Windows limitation with a restriction on the size of arguments being passed to a program. 

So size `127` +/- 2 and larger might be too big, depending on the image.

Once you hit that size (~100K bits), it's going to take an enormous amount of time to try to find an arbitrary prime value of that size, so I don't think it'll be worth the investment trying to adjust it further 😛.
